### ISSUE TITLE
Some imports owl files not generated without error message

### ISSUE THREAD

**Issue by citmejia** [INCATools/ontology-starter-kit#41]
Hi,

I was generating the imports owl files of my ontology by  typing "make imports/foo_import.owl" using this Makefile

 https://github.com/citmejia/Microbial-Conditions-Ontology/blob/master/src/ontology/Makefile

 Some of them were generated. However, imports from EFO, NPO, and SIO were not generated and no error message came out. In addition, when I tried to generate EO owl file the error below came out.  What can I do?

Citlallis-MacBook-Pro:ontology citlallimejiaalmonte$ make imports/eo_import.owl
owltools http://purl.obolibrary.org/obo/eo.owl --remove-annotation-assertions -l -s -d --remove-dangling-annotations  -o mirror/eo.owl
2018-04-16 11:44:39,372 ERROR (CommandRunner:4646) could not parse:http://purl.obolibrary.org/obo/eo.owl
org.semanticweb.owlapi.io.OWLOntologyCreationIOException: https://raw.githubusercontent.com/Planteome/plant-environment-ontology/master/plant-environment-ontology.obo.owl
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:227)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1250)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1204)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1104)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1060)
	at owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:163)
	at owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:150)
	at owltools.io.ParserWrapper.parse(ParserWrapper.java:132)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:4634)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
Caused by: java.io.FileNotFoundException: https://raw.githubusercontent.com/Planteome/plant-environment-ontology/master/plant-environment-ontology.obo.owl
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStreamFromContentEncoding(AbstractOWLParser.java:170)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:132)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:246)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:72)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:217)
	... 11 more
Caused by: java.io.FileNotFoundException: https://raw.githubusercontent.com/Planteome/plant-environment-ontology/master/plant-environment-ontology.obo.owl
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2982)
	at java.net.URLConnection.getContentEncoding(URLConnection.java:523)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:410)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:127)
	... 14 more
make: *** [mirror/eo.owl] Error 1

**Comment by cmungall** [comment]
Hi @citmejia 

EO has been replaced by PECO

We had an issue in our tracker to communicate this to a wider community but are behind on this:
https://github.com/Planteome/plant-experimental-conditions-ontology/issues/95

I have updated the EO page on OBO

http://obofoundry.org/ontology/eo.html

To include a migration guide (basically just do a search and replace of EO_ to PECO_)

**Comment by citmejia** [comment]
Hi Chris,

Thanks a lot for your quick response.


I think I managed to replace EO by PECO and generated appropriate imports,
but I still don't understand why imports from  EFO, NPO, and SIO didn't
extract any classes neither for the import file nor for the mirror. Both
owl files have this message

""

But no classes were included in the generated files.

Best regards,
C.

2018-04-18 14:27 GMT-05:00 Chris Mungall <notifications@github.com>:
